dist: xenial
language: python

python:
- 2.7
- 3.5
- 3.6
- 3.7
- 3.8
- 3.9
- 3.10-dev
- pypy2.7-6.0
- pypy3.5

install:
- pip install tox-travis
script:
- tox

stages:
- lint
- test
#- deploy

matrix:
  allow_failures:
  - env: TOXENV=flake8
  - env: TOXENV=pylint
  - env: TOXENV=bandit
  - python: 3.10-dev

jobs:
  include:
  #- { stage: lint, python: 3.7, env: TOXENV=flake8 }
  #- { stage: lint, python: 3.7, env: TOXENV=pylint }
  #- { stage: lint, python: 3.7, env: TOXENV=bandit }
  - { stage: lint, python: 3.7, env: TOXENV=readme }

  #- stage: deploy
  #  install: skip
  #  script: skip
  #  deploy:
  #    provider: pypi
  #    distributions: sdist bdist_wheel
  #    user: cool-RR
  #    password:
  #      secure: <your-pypi-password-here-encrypted-using-the-travis-cli>
  #    on:
  #      tags: true
